"""Configuration parameters for this example."""

DATABASE_FILE = "database.sqlite"
NUM_REPETITIONS = 1
NUM_SIMULATORS = 15
POPULATION_SIZE = 30
OFFSPRING_SIZE = 15
NUM_GENERATIONS = 10
CMAES_NUM_GENERATIONS = 10
CMAES_POP_SIZE = 10
CMAES_INITIAL_STD = 0.5
CMAES_BOUNDS = [-5.0, 5.0]
